### ISSUE TITLE
`Failed to write proc data: userAgentData [object Object]`, data is `null`

### ISSUE THREAD

**Issue by james-pre** [ecmaos/ecmaos#1]
Occurs at this line:
https://github.com/ecmaos/ecmaos/blob/2259136f8d7a6dc44523e2cf9584f69183a8859d/core/kernel/src/tree/kernel.ts#L811

1. Errors don't appear to be concatenated to strings correctly. When debugging, the error `.toString()` and `+''` return the error string, so I'm not sure why `[object Object]` is printed

2. The caught error happens in `Kernel.registerProc`:

`Error: EINVAL: Iterables and streams not supported, '/userAgentData'`

Oddly enough, this occurs due to the data passed to `fs.promises.writeFile` being `null`. I've updated the error message in [`fs.promises.writeFile`](https://github.com/zen-fs/core/blob/v1.4.2/src/emulation/promises.ts#L600).

The data is `null` due to this line:
https://github.com/ecmaos/ecmaos/blob/2259136f8d7a6dc44523e2cf9584f69183a8859d/core/kernel/src/tree/kernel.ts#L787

You might want to add handling for `null` values.

**Comment by mathiscode** [comment]
Good catch and elegant fix! Much appreciated! 💪😄
